app_name: dashboard-app
version: 1
connections:
  - config : !LocalStorage
      details:
        path: .
      tables:
        - !Table
          name: eth_addresses
          config: !CSV
            path: data
            extension: .csv
    name: local
  - config: !Ethereum
      provider: !Log
        wss_url: wss://mainnet.infura.io/ws/v3/6c4873a01d144bdeaaf2588a743cf8e9
        contracts:
          - name: usdt
            address: 0xdAC17F958D2ee523a2206206994597C13D831ec7
            abi: >
              [{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_upgradedAddress","type":"address"}],"name":"deprecate","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"deprecated","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_evilUser","type":"address"}],"name":"addBlackList","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"upgradedAddress","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"balances","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"maximumFee","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"_totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[],"name":"unpause","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_maker","type":"address"}],"name":"getBlackListStatus","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"},{"name":"","type":"address"}],"name":"allowed","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"paused","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"who","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[],"name":"pause","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"getOwner","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"newBasisPoints","type":"uint256"},{"name":"newMaxFee","type":"uint256"}],"name":"setParams","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"amount","type":"uint256"}],"name":"issue","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"amount","type":"uint256"}],"name":"redeem","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"},{"name":"_spender","type":"address"}],"name":"allowance","outputs":[{"name":"remaining","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"basisPointsRate","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"isBlackListed","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_clearedUser","type":"address"}],"name":"removeBlackList","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"MAX_UINT","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_blackListedUser","type":"address"}],"name":"destroyBlackFunds","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"inputs":[{"name":"_initialSupply","type":"uint256"},{"name":"_name","type":"string"},{"name":"_symbol","type":"string"},{"name":"_decimals","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"amount","type":"uint256"}],"name":"Issue","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"amount","type":"uint256"}],"name":"Redeem","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"newAddress","type":"address"}],"name":"Deprecate","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"feeBasisPoints","type":"uint256"},{"indexed":false,"name":"maxFee","type":"uint256"}],"name":"Params","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"_blackListedUser","type":"address"},{"indexed":false,"name":"_balance","type":"uint256"}],"name":"DestroyedBlackFunds","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"_user","type":"address"}],"name":"AddedBlackList","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"_user","type":"address"}],"name":"RemovedBlackList","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"owner","type":"address"},{"indexed":true,"name":"spender","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Approval","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[],"name":"Pause","type":"event"},{"anonymous":false,"inputs":[],"name":"Unpause","type":"event"}]          
          
        filter:
        from_block: 16262470
        addresses:
          - 0xdAC17F958D2ee523a2206206994597C13D831ec7
    name: eth_conn

sources:
  - name: usdt_Transfer
    table_name: usdt_Transfer
    connection: eth_conn
    
  - name: off_chain
    table_name: eth_addresses
    connection: local  

sql: |

 WITH data AS (
 SELECT value, NOW() AS currtime
 FROM usdt_Transfer
 )
 SELECT
 t.window_start AS start, t.window_end AS end, (SUM(t.value))/1e6 AS traded_volume, AVG(t.value) AS averg_transaction
 INTO sum
 FROM TUMBLE(data, currtime,'24 HOURS') t
 GROUP BY t.window_start, t.window_end;

 SELECT from, to, value
 INTO transfers
 FROM usdt_Transfer;
 
 WITH buyers_data AS (
 SELECT value, to, NOW() as currtime
 FROM usdt_Transfer
 )
 SELECT t.window_start AS start, t.window_end AS end, t.to AS BuyerAddress, (SUM(t.value))/1000000 AS amount_bought
 INTO buyers
 FROM TUMBLE(buyers_data, currtime,'24 HOURS') t
 GROUP BY t.window_start, t.window_end, t.to;
 
 
 WITH sellers_data AS (
 SELECT value, from, NOW() as currtime
 FROM usdt_Transfer
 )
 SELECT t.window_start AS start, t.window_end AS end, t.from AS SellerAddress, (SUM(t.value))/1000000 AS amount_sold
 INTO sellers
 FROM TUMBLE(sellers_data, currtime,'24 HOURS') t
 GROUP BY t.window_start, t.window_end, t.from;

 SELECT e.Address AS seller_address,e.Name as Name, e.Label AS Authenticity
 INTO identified_sellers 
 FROM 
 usdt_Transfer u
 JOIN off_chain e
 ON u.from = e.Address;

 SELECT e.Address AS buyer_address,e.Name as Name, e.Label AS Authenticity
 INTO identified_buyers
 FROM 
 usdt_Transfer u
 JOIN off_chain e
 ON u.to = e.Address;

 SELECT DISTINCT from
 INTO distinct_sellers
 FROM usdt_Transfer;

 SELECT DISTINCT  to 
 INTO distinct_buyers
 FROM usdt_Transfer;
 
endpoints:

  # USDT Transfers
  - name: transfers
    table_name: transfers
    path: /transfers

  # Aggregated Traded Volume
  - name: sum
    table_name: sum
    path: /sum
    
  # Top Buyers
  - name: buyers
    table_name: buyers
    path: /buyers


  # Top Sellers  
  - name: sellers
    table_name: sellers
    path: /sellers

  # Identified Sellers 
  - name: identified_sellers
    table_name: identified_sellers
    path: /identified_sellers

  # Identified Buyers
  - name: identified_buyers
    table_name: identified_buyers
    path: /identified_buyers
    
  # Distinct Sellers   
  - name: distinct_sellers
    table_name: distinct_sellers
    path: /distinct_sellers

  # Distinct Buyers
  - name: distinct_buyers
    table_name: distinct_buyers
    path: /distinct_buyers